<a href="https://colab.research.google.com/github/MukeshRanaDS/Deep-Learning-Computer-Vision-/blob/main/Tensorflow_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

tf.test.gpu_device_name()

'/device:GPU:0'

In [ ]:
# 0-D Tensor
print(tf.constant(4))

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
# 1-D Tensor (pack of 0-D tensors)
print(tf.constant([1,2,3.9,]))

# declare the tensor as float32
print(tf.constant([1,2,3.9,], dtype=tf.float32))

# Convert the tensor as int32 using casting
print(tf.cast(tf.constant([1,2,3.9,], dtype=tf.float32), dtype=tf.int32))

tf.Tensor([1.  2.  3.9], shape=(3,), dtype=float32)
tf.Tensor([1.  2.  3.9], shape=(3,), dtype=float32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
# 2-D tensor (pack of 1-D tensors)
print(tf.constant([[1,2,3], [5,6.3,7], [5,3.4,7.1]]))

tf.Tensor(
[[1.  2.  3. ]
 [5.  6.3 7. ]
 [5.  3.4 7.1]], shape=(3, 3), dtype=float32)


In [ ]:
# 3-D tensor (pack of 2-d tensors)
print(tf.constant([[[1,2,3], [5,3.4,7.1]], [[5,6.3,7], [5,3.4,7.1]]]))
print(tf.constant([[[1,2,3], [5,3.4,7.1]], [[5,6.3,7], [5,3.4,7.1]]]).shape)
print(tf.constant([[[1,2,3], [5,3.4,7.1]], [[5,6.3,7], [5,3.4,7.1]]]).ndim)

tf.Tensor(
[[[1.  2.  3. ]
  [5.  3.4 7.1]]

 [[5.  6.3 7. ]
  [5.  3.4 7.1]]], shape=(2, 2, 3), dtype=float32)
(2, 2, 3)
3


In [21]:
tf.ones(2)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

## Einsum Operator

In [1]:
import numpy as np

In [ ]:
A = np.array([[2, 6, 5, 2],
              [2, ]])